### ISSUE TITLE
The title is still misplaced sometimes in the current `master` branch

### ISSUE THREAD

**Issue by ben-z** [PackAnts/landing-pages#12]
Perhaps we should eliminate the top bar animation when the page loads.

![](https://www.dropbox.com/s/zwwt045cdutxgjl/2016-02-15-210946_1347x751.png?dl=1)

**Comment by DerekFei** [comment]
I'll fix the background missing and the title problem this week. (Those problem are not exist on my laptop at all. it's so hard to find out the reason for them....)

Date: Mon, 15 Feb 2016 18:12:53 -0800

**Comment by ben-z** [comment]
True, it would be better to remove the title animation all together I think.

**Comment by ben-z** [comment]
This should be fixed in f2df5ea57805bfb181da94ee28f034e8adf925b6
